### ISSUE TITLE
error binance, dont close trades

### ISSUE THREAD

**Issue by jordanlanch** [Haehnchen/crypto-trading-bot#154]
![image](https://user-images.githubusercontent.com/24902096/90929565-91f0f300-e3be-11ea-8314-d1ed94870b14.png)

**Comment by Haehnchen** [comment]
a log entry would be helpful and some more info, but i issues a lot as changed since issue creation. for me all binance exchanges implemementations are working fine on daily base.

closing this for now

**Comment by Wladastic** [comment]
@Haehnchen maybe share some basic "new" configs,
My trades also cannot close due to 
`
Order create canceled:{"id":stuff,"symbol":"HOTUSDT","side":"short","price":-0.0005113,"amount":-115123,"type":"limit","options":{"close":true,"adjust_price":true,"post_only":true}} - "TypeError: order.setStopPrice is not a function"
--`
