### ISSUE TITLE
Tulind Indicator Usage

### ISSUE THREAD

**Issue by gelinger777** [Haehnchen/crypto-trading-bot#189]
Can somebody hint how in strategies and  buildIndicator add tulind indicator?  I need a Tulind indicator which is not defined in the indicators.js

**Comment by egisz** [comment]
Hi, 
> @egisz could you give an example how to implement tulind for example ( tema indicator with variable lengthes 50/200) which I can pass in strategy at #189 ?

**tema** indicator actually is included in indicators.j:
As you can see it calls function from[ tulind library](https://github.com/TulipCharts/tulipnode#readme)  :
https://github.com/Haehnchen/crypto-trading-bot/blob/40f71cab7c9bf73225e9ec00e177c46f74efd34a/src/utils/indicators.js#L152

I admit it's hard to figure out parameters. Bassically you can expects same parameters which are passed as default values  to tulind function, in this case it is 
` options: { length: 9 } `

So in order to add tema indicator you need to call indicatorBuilder with parameters like this: 
` indicatorBuilder.add('myTemaIndicator', 'tema', options.period, { length: 21 }); `

**Comment by gelinger777** [comment]
@egisz  first of all thanks for helping out. So did I understand right, if I want to add let;s say  kama mouving average i need to add into indicators.js 
 kama: (...args) => executeTulindIndicator(...args, { options: { length: 9 } }),  and length:9 is the default value only and it will be replaced with 21  from strategy?

**Comment by gelinger777** [comment]
Ok @egisz  I could make Kama indicator work, but for example linreg brings me NaN values... can it be that the backtester is not feeding enough points?

**Comment by gelinger777** [comment]
ok i have debugged. Seems just adding to that line is not enough as it's not passing the source array to calculate. I have even added  kama to this line 
`
https://github.com/Haehnchen/crypto-trading-bot/blob/40f71cab7c9bf73225e9ec00e177c46f74efd34a/src/utils/indicators.js#L136

also no result. I how to properly pass source ?

**Comment by gelinger777** [comment]
Ok I have found the solution. You have to  add indicator in following manner to work properly 
```
  indicatorBuilder.add('ema2', 'kama', options.period, {
      length: 37
    },'close');
```
thanks

**Comment by egisz** [comment]
@gelinger777, feel free to fork repository and create pull request with additional indicators.

**Comment by gelinger777** [comment]
@egisz  will do. Smarter approach would be to make it like it was done back in gekko. And  in gekko  it was done dynamic, so that you could just pass the name of the indicator and params and get the result and use it, without need to hardcode it.

**Comment by egisz** [comment]
I'll try a bit later
