### ISSUE TITLE
Backtest results

### ISSUE THREAD

**Issue by jbrodriguez** [Haehnchen/crypto-trading-bot#279]
I just ran a backtest for BTCUSD on binance_futures and these are the results

![Screen Shot 2021-12-15 at 19 34 55](https://user-images.githubusercontent.com/1305422/146286451-9f5ae4bc-f4bd-485d-8655-42cb997167b6.png)

Any thoughts on
- Why it started trading on Dec 12, instead of Dec 10 when there was a dip ?
- Why there was a close signal on Dec 13 ?
-  It seems to be buying high and selling low (except for the last buy) ?

I just used the default options for the dip_catcher strategy

**Comment by Wladastic** [comment]
What were the params you initiated this with?Always make sure to play with different params to see what worked best for the currency pairs.GreetsAm 16.12.2021 01:38 schrieb "Juan B. Rodriguez" ***@***.***>:
I just ran a backtest for BTCUSD on binance_futures and these are the results

Any thoughts on
Why it started trading on Dec 12, instead of Dec 10 when there was a dip ?Why there was a close signal on Dec 13 ?It seems to be buying high and selling low (except for the last buy) ?
I just used the default options for the dip_catcher strategy

**Comment by jbrodriguez** [comment]
ok, thanks, these were the params

![Screen Shot 2021-12-16 at 09 58 55](https://user-images.githubusercontent.com/1305422/146395341-2a05f44b-212d-4381-a05d-d2c99a71cef7.png)

which are the default for the strategy, I've played a bit with them, but got similar results.

Will try to play some more.

**Comment by Wladastic** [comment]
Period of 9 is too high for the low settingI set them on 4.And high param is on 5Am 16.12.2021 15:59 schrieb "Juan B. Rodriguez" ***@***.***>:
ok, thanks, these were the params

which are the default for the strategy, I've played a bit with them, but got similar results.
Will try to play some more.
